class SceneCharacterCooccurrences:
    def __init__(self):
        self.cooccurrences = {}

    def add_cooccurrence(self, character1, character2):
        pair = tuple(sorted([character1, character2]))
        self.cooccurrences[pair] = self.cooccurrences.get(pair, 0) + 1

    def display_cooccurrences(self):
        for pair, count in self.cooccurrences.items():
            print(f"{pair[0]} and {pair[1]}: {count} times")

# Example usage
all_scenes_cooccurrences = SceneCharacterCooccurrences()

# Adding co-occurrences based on the provided information
all_scenes_cooccurrences.add_cooccurrence("First Witch", "Second Witch")
all_scenes_cooccurrences.add_cooccurrence("First Witch", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("Second Witch", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "MALCOLM")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "DONALBAIN")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("MALCOLM", "DONALBAIN")
all_scenes_cooccurrences.add_cooccurrence("MALCOLM", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("DONALBAIN", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MALCOLM", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "BANQUO")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "First Witch")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Second Witch")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "ANGUS")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "MACBETH")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "BANQUO")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "ANGUS")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "Messenger")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "MACBETH")
all_scenes_cooccurrences.add_cooccurrence("DUNCAN", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("ANGUS", "LADY MACBETH")
# Adding co-occurrences from the latest scene
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "DUNCAN")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "SEWER")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Messenger")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "SEWER")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "Messenger")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "DUNCAN")
# Adding co-occurrences from Act II, Scene 1
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "BANQUO")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "FLEANCE")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Servant")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "FLEANCE")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "Servant")
all_scenes_cooccurrences.add_cooccurrence("FLEANCE", "Servant")
# Adding co-occurrences from Act II, Scene 2
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "MACBETH")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "Servant")
# Adding co-occurrences from Act II, Scene 3
all_scenes_cooccurrences.add_cooccurrence("Porter", "MACDUFF")
all_scenes_cooccurrences.add_cooccurrence("Porter", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("Porter", "MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "BANQUO")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "MALCOLM")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "DONALBAIN")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "MALCOLM")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "DONALBAIN")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "BANQUO")
# Adding co-occurrences from Act II, Scene 4
all_scenes_cooccurrences.add_cooccurrence("ROSS", "Old Man")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "MACDUFF")
all_scenes_cooccurrences.add_cooccurrence("Old Man", "MACDUFF")
# Adding co-occurrences from Act III, Scene 1
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "MACBETH")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Lords")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Lords")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "Lords")
# Adding co-occurrences from Act III, Scene 1
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "First Murderer")
all_scenes_cooccurrences.add_cooccurrence("First Murderer", "Second Murderer")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Second Murderer")
# Adding co-occurrences from Act III, Scene 2
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "Servant")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Servant")
# Adding co-occurrences from Act III, Scene 3
all_scenes_cooccurrences.add_cooccurrence("First Murderer", "Third Murderer")
all_scenes_cooccurrences.add_cooccurrence("First Murderer", "Second Murderer")
all_scenes_cooccurrences.add_cooccurrence("Third Murderer", "Second Murderer")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "First Murderer")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "Second Murderer")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "Third Murderer")
all_scenes_cooccurrences.add_cooccurrence("BANQUO", "FLEANCE")
# Adding co-occurrences from Act III, Scene 4
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Lords")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "First Murderer")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Second Murderer")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Third Murderer")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "GHOST OF BANQUO")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "First Murderer")
# Adding co-occurrences from Act III, Scene 5
all_scenes_cooccurrences.add_cooccurrence("First Witch", "Second Witch")
all_scenes_cooccurrences.add_cooccurrence("First Witch", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("Second Witch", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("First Witch", "HECATE")
all_scenes_cooccurrences.add_cooccurrence("Second Witch", "HECATE")
all_scenes_cooccurrences.add_cooccurrence("Third Witch", "HECATE")
# Adding co-occurrences from Act III, Scene 6
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Lord")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Duncan")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Macbeth")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Malcolm")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Donalbain")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Banquo")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Fleance")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Macduff")
all_scenes_cooccurrences.add_cooccurrence("Lord", "Duncan")
all_scenes_cooccurrences.add_cooccurrence("Lord", "Macbeth")
all_scenes_cooccurrences.add_cooccurrence("Lord", "Fleance")
all_scenes_cooccurrences.add_cooccurrence("Macbeth", "Duncan")
all_scenes_cooccurrences.add_cooccurrence("Macbeth", "Banquo")
all_scenes_cooccurrences.add_cooccurrence("Duncan", "Malcolm")
all_scenes_cooccurrences.add_cooccurrence("Duncan", "Donalbain")
all_scenes_cooccurrences.add_cooccurrence("Malcolm", "Donalbain")
all_scenes_cooccurrences.add_cooccurrence("Macduff", "Edward")
all_scenes_cooccurrences.add_cooccurrence("Macduff", "Northumberland")
all_scenes_cooccurrences.add_cooccurrence("Macduff", "Siward")
# Adding co-occurrences from Act IV, Scene 1
all_scenes_cooccurrences.add_cooccurrence("First Witch", "Second Witch")
all_scenes_cooccurrences.add_cooccurrence("First Witch", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("Second Witch", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("First Witch", "HECATE")
all_scenes_cooccurrences.add_cooccurrence("Second Witch", "HECATE")
all_scenes_cooccurrences.add_cooccurrence("Third Witch", "HECATE")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "First Witch")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Second Witch")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "Third Witch")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "HECATE")
all_scenes_cooccurrences.add_cooccurrence("MACBETH", "LENNOX")
# Adding co-occurrences from Act IV, Scene 2
all_scenes_cooccurrences.add_cooccurrence("LADY MACDUFF", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("LADY MACDUFF", "Son")
all_scenes_cooccurrences.add_cooccurrence("LADY MACDUFF", "Messenger")
all_scenes_cooccurrences.add_cooccurrence("LADY MACDUFF", "First Murderer")
all_scenes_cooccurrences.add_cooccurrence("Son", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("Son", "Messenger")
all_scenes_cooccurrences.add_cooccurrence("Son", "First Murderer")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "Messenger")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "First Murderer")
all_scenes_cooccurrences.add_cooccurrence("Messenger", "First Murderer")
# Adding co-occurrences from Act V, Scene 3
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "MALCOLM")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "Doctor")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "Wife")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "Children")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "Servants")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("MACDUFF", "King")
all_scenes_cooccurrences.add_cooccurrence("MALCOLM", "Doctor")
all_scenes_cooccurrences.add_cooccurrence("MALCOLM", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("MALCOLM", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("Doctor", "ROSS")
all_scenes_cooccurrences.add_cooccurrence("Doctor", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "Wife")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "Children")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "Servants")
all_scenes_cooccurrences.add_cooccurrence("ROSS", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("Wife", "Children")
all_scenes_cooccurrences.add_cooccurrence("Wife", "Servants")
all_scenes_cooccurrences.add_cooccurrence("Wife", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("Children", "Servants")
all_scenes_cooccurrences.add_cooccurrence("Children", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("Servants", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("King", "Heaven")
all_scenes_cooccurrences.add_cooccurrence("Doctor", "Gentlewoman")
all_scenes_cooccurrences.add_cooccurrence("Doctor", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("Doctor", "Banquo")
all_scenes_cooccurrences.add_cooccurrence("Doctor", "God")
all_scenes_cooccurrences.add_cooccurrence("Gentlewoman", "LADY MACBETH")
all_scenes_cooccurrences.add_cooccurrence("Gentlewoman", "Banquo")
all_scenes_cooccurrences.add_cooccurrence("Gentlewoman", "God")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "Banquo")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "God")
all_scenes_cooccurrences.add_cooccurrence("LADY MACBETH", "Arabia")
all_scenes_cooccurrences.add_cooccurrence("MENTEITH", "CAITHNESS")
all_scenes_cooccurrences.add_cooccurrence("MENTEITH", "ANGUS")
all_scenes_cooccurrences.add_cooccurrence("MENTEITH", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("MENTEITH", "Malcolm")
all_scenes_cooccurrences.add_cooccurrence("MENTEITH", "Siward")
all_scenes_cooccurrences.add_cooccurrence("MENTEITH", "Macduff")
all_scenes_cooccurrences.add_cooccurrence("CAITHNESS", "ANGUS")
all_scenes_cooccurrences.add_cooccurrence("CAITHNESS", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("CAITHNESS", "Malcolm")
all_scenes_cooccurrences.add_cooccurrence("CAITHNESS", "Siward")
all_scenes_cooccurrences.add_cooccurrence("CAITHNESS", "Macduff")
all_scenes_cooccurrences.add_cooccurrence("ANGUS", "LENNOX")
all_scenes_cooccurrences.add_cooccurrence("ANGUS", "Malcolm")
all_scenes_cooccurrences.add_cooccurrence("ANGUS", "Siward")
all_scenes_cooccurrences.add_cooccurrence("ANGUS", "Macduff")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Malcolm")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Siward")
all_scenes_cooccurrences.add_cooccurrence("LENNOX", "Macduff")
# Displaying the updated results
all_scenes_cooccurrences.display_cooccurrences()
